### ISSUE TITLE
How to deal with default values?

### ISSUE THREAD

**Issue by bebraw** [AppliedMathematicsANU/plexus-form#11]
Let's say I want to have my form to have default values (ie. specific strings, numbers, selections). What would be a nice way to deal with that? As far as I understand `json-schema` doesn't provide official support for this. That said having a `default` field available might resolve this nicely.

**Comment by bebraw** [comment]
I wonder if this is needed even. You can set default values through Form `values` property already. Even then it would be possible to keep the logic out of `plexus-form` due to this.

What do you think?

**Comment by odf** [comment]
Since `json-schema` does not define default values, and like you said, it is easy to handle the logic outside of `plexus-form`, I am leaning towards not implementing this.

**Comment by bebraw** [comment]
Yeah, let's skip this.
