### ISSUE TITLE
Update to current React

### ISSUE THREAD

**Issue by martijnvermaat** [AppliedMathematicsANU/plexus-form#16]
Could you consider pushing a release depending on current React (0.12.2)?

**Comment by odf** [comment]
I'm still trying to make myself believe that React 0.12 never happened, but I fear I won't be able to much longer. :-) So yes, I will definitely get onto that very soon.

**Comment by odf** [comment]
Done!
Release 0.1.0 depends on React 0.12.2 and produces no deprecation warnings.
Release 0.0.19 is the last one based on React 0.10.x or earlier.
