### ISSUE TITLE
Loosen semver to allow usage with React 0.13 and beyond?

### ISSUE THREAD

**Issue by bebraw** [AppliedMathematicsANU/plexus-form#26]
Now the dep is like `"react": "~0.12.2"`. It would be better to have something looser in place. If you want something really loose, you could try `"react": ">=0.12.2 <1.0.0"`.

**Comment by killercup** [comment]
I'm currently using @bebraw's fork (`npm i -S "bebraw/plexus-form#ababe1c619b3a1fc27a08c4c3d9e1c545d95f19b"`) for exactly this losend requirement.

**Comment by odf** [comment]
Fixed in v0.1.2.
