### ISSUE TITLE
Components shouldn't try to use this.props.key

### ISSUE THREAD

**Issue by martijnvermaat** [AppliedMathematicsANU/plexus-form#34]
From React 0.12 (I think), `key` and `ref` are now reserved prop names since passing them has a separate meaning. Hence, a component shouldn't try to read `this.props.key`.

This is done in, for example, `InputField` and `InputWrapper` where it indeed yields `undefined`.

I think the original idea behind using `key` here is still useful (e.g., to properly set `id` and `htmlFor`), but a different property name should be used.

**Comment by odf** [comment]
Ah yes, looks like it is used all over the place. Thanks for catching this one!

**Comment by martijnvermaat** [comment]
A simple renaming will probably do, but there might be places where you also still want to have a `key`. I didn't look closely at that, but the `key` for `<option>` in `SelectionField` should stay for example.

**Comment by odf** [comment]
I had a quick look through the code and it seems that we'll want to duplicate the `key` prop that is constructed in `fields/make` into one that can be read within a render method. I think `label` would fit nicely. Then every use of `this.props.key` will have to be replaced by `this.props.label`. We still want to keep setting the `key` prop to disambiguate fields, so I won't be renaming `key` when it's in the receiving position.

I'll get to this right away and see if anything breaks.

**Comment by odf** [comment]
Fixed in d81ee5d.
