### ISSUE TITLE
Array re-order values

### ISSUE THREAD

**Issue by ismaelga** [AppliedMathematicsANU/plexus-form#47]
Would this be a good feature to send as a PR?

I'm actually implementing this for my own usage, so I was thinking if it could be helpful for others.
My current idea is to provide the functions `canMoveUp`, `canMoveDown`, `moveUp` and `moveDown` as props for sections inside an array. Does this sound good for you guys?

I might submit a PR later today (maybe in a hour or so).

**Comment by ismaelga** [comment]
Meanwhile I've added more features to my fork, namely:

- Added a prop for SectionWrapper to remove item
- Append property to title on arrays (title or name properties or one specified in x-hints)

Let me know if any of them are good for a PR.

**Comment by odf** [comment]
That all sounds nice, but I will no longer maintain this project.
